version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    image: gaiathon25-hub/app:test
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongodb:27017/test
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    command: ["npm", "run", "test"]

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=test
    command: ["mongod", "--noauth"]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379" 